title: Michael Marchand
email: michaeldavidmarchand@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Learning. One day at a time.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://MarchandMD.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag

google_analytics: G-NXV2EVGJL1

jekyll-archives:
  enabled: "all"
  layout: default
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/category/:name/"

collections:
  code_challenges:
    output: true
  projects:
    output: true

include:
  - _code_challenges
  - _edabit
  - leetcode
  - _projects
  - blog

show_excerpts:
  - true

page_excerpts:
  - true

paginate: 8
paginate_path: "/blog/page:num/"

linkedin_username: mmarchand1
github_username: marchandmd

header_pages:
  - portfolio.md
  - Code_Challenges.md
  - about.md
  - index.html
